### PR TITLE
Add docker compose and docker version detection

### PR DESCRIPTION
**Pull request by spiritLHLS**
Due to this problem:
```
root@spiritlhl:~/webvirtcloud# ./webvirtcloud.sh start
 __        __   _  __     ___      _    ____ _                 _ 
 \ \      / ___| |_\ \   / (_)_ __| |_ / ___| | ___  _   _  __| |
  \ \ /\ / / _ | '_ \ \ / /| | '__| __| |   | |/ _ \| | | |/ _` |
   \ V  V |  __| |_) \ V / | | |  | |_| |___| | (_) | |_| | (_| |
    \_/\_/ \___|_.__/ \_/  |_|_|   \__|\____|_|\___/ \__,_|\__,_|
                                                                        
Building WebVirtCloud...
[+] Building 9.9s (13/13) FINISHED                                                                                                                          docker:default
 => [backend internal] load build definition from Dockerfile.backend                                                                                                  0.0s
 => => transferring dockerfile: 1.40kB                                                                                                                                0.0s
 => [backend internal] load .dockerignore                                                                                                                             0.0s
 => => transferring context: 109B                                                                                                                                     0.0s
 => [backend internal] load metadata for docker.io/library/python:3.10-alpine                                                                                         0.8s
 => CACHED [backend backend-deps 1/6] FROM docker.io/library/python:3.10-alpine@sha256:7e73eab259b777c76ad93e42180d468f326eff315c212bc80d4dffdf4695163a               0.0s
 => [backend internal] load build context                                                                                                                             0.0s
 => => transferring context: 27.15kB                                                                                                                                  0.0s
 => [backend backend-deps 2/6] RUN apk add --no-cache gcc g++ pango fontconfig ttf-freefont font-noto terminus-font                        musl-dev mariadb-dev libf  3.9s
 => [backend backend-deps 3/6] WORKDIR /requirements                                                                                                                  0.0s 
 => [backend backend-deps 4/6] COPY ./webvirtbackend/requirements/production.txt /requirements/requirements.txt                                                       0.0s 
 => [backend backend-deps 5/6] COPY ./optional-requirements.txt* /requirements/                                                                                       0.0s 
 => [backend backend-deps 6/6] RUN pip install -U uv;     uv pip install --system -r requirements.txt;     if [ -e optional-requirements.txt ]; then     uv pip inst  4.0s 
 => [backend backend 1/2] WORKDIR /backend                                                                                                                            0.0s 
 => [backend backend 2/2] COPY ./webvirtbackend/ /backend/                                                                                                            0.0s 
 => [backend] exporting to image                                                                                                                                      1.1s 
 => => exporting layers                                                                                                                                               1.1s 
 => => writing image sha256:0393f785a77ffcec6ce04e908bdbb062e3b0656a5b82627c5c9741214e09f367                                                                          0.0s 
 => => naming to docker.io/library/webvirtcloud:backend                                                                                                               0.0s 
Start WebVirtCloud...
[+] Running 0/0
 ⠋ Container webvirtcloud-frontend  Creating                                                                                                                          0.0s 
 ⠋ Container webvirtcloud-rabbitmq  Creating                                                                                                                          0.0s 
 ⠋ Container webvirtcloud-mariadb   Creating                                                                                                                          0.0s 
can't set healthcheck.start_interval as feature require Docker Engine v25 or later
```
I fixed it.

### CODE REVIEW

**Comment by spiritLHLS** [comment]
Incidentally, your deployment method seems to require a bound domain name by default, and doesn't provide a way to deploy without a domain name.

**Comment by retspen** [comment]
That is good idea. Thank you!

**Comment by spiritLHLS** [comment]
> That is good idea. Thank you!

Is it possible to deploy using a domain-less approach? Different pages can use different ports.

**Comment by retspen** [comment]
I'm not sure what you mean. Can you please explain or give an example?

**Comment by spiritLHLS** [comment]
> I'm not sure what you mean. Can you please explain or give an example?

```
. /webvirtcloud.sh env
```

Requires the user to enter the domain name

I don't want to use a domain name and only use an IP address with different ports to display the page that corresponds to your 

```
BASE_DOMAIN=webvirtcloud.app
API_DOMAIN=api.webvirtcloud.app
ASSETS_DOMAIN=assets.webvirtcloud.app
CLIENT_DOMAIN=client.webvirtcloud.app
MANAGE_DOMAIN=manage.webvirtcloud.app
CONSOLE_DOMAIN=console.webvirtcloud.app
```

**Comment by CloudRack-Development** [comment]
> > I'm not sure what you mean. Can you please explain or give an example?
> 
> ```
> . /webvirtcloud.sh env
> ```
> 
> Requires the user to enter the domain name
> 
> I don't want to use a domain name and only use an IP address with different ports to display the page that corresponds to your
> 
> ```
> BASE_DOMAIN=webvirtcloud.app
> API_DOMAIN=api.webvirtcloud.app
> ASSETS_DOMAIN=assets.webvirtcloud.app
> CLIENT_DOMAIN=client.webvirtcloud.app
> MANAGE_DOMAIN=manage.webvirtcloud.app
> CONSOLE_DOMAIN=console.webvirtcloud.app
> ```

People using cloudflare zerotrust proxies can make use of this and allow users to install CF onto server allowing to proxie the needed ports with a SSL anyways to a domain id one up this myself @retspen.

**Comment by retspen** [comment]
Can you create issue? I think we can create this like option.

**Comment by spiritLHLS** [comment]
> Can you create issue? I think we can create this like option.

https://github.com/webvirtcloud/webvirtcloud/issues/21

Done

**Pull request merged**
